server {
    listen 80;
    server_name _;

    client_max_body_size 220m;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript application/xml image/svg+xml;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    location /healthz {
        return 200 "ok";
        add_header Content-Type text/plain;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
